name: Fly Deploy
on:
  push:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set Fly Secrets
        run: |
          flyctl secrets set APPOPTIONS__DbConnectionString="${{secrets.DBCONNECTIONSTRING}}"
          flyctl secrets set APPOPTIONS__JwtSecret="${{secrets.JWT_SECRET}}"
          flyctl secrets set APPOPTIONS__PASS="${{secrets.PASS}}"
      - name: Deploy
        run: flyctl deploy