# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APPOPTIONS__DbConnectionString: ${{secrets.DBCONNECTIONSTRING}}
          APPOPTIONS__JwtSecret: ${{secrets.JWT_SECRET}}
          APPOPTIONS__PASS: ${{secrets.PASS}}