name: Deploy to Google Cloud Run

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: yoalex
          region: europe-north1
          source: .
          flags: --allow-unauthenticated
          env_vars: |
            APPOPTIONS__DbConnectionString=${{ secrets.DBCONNECTIONSTRING }}
            APPOPTIONS__JwtSecret=${{secrets.JWT_SECRET}}
            APPOPTIONS__Pass=${{secrets.PASS}}
            APPOPTIONS__REDIS_HOST= ${{secrets.REDIS_HOST}}
            APPOPTIONS__REDIS_PASS= ${{secrets.REDIS_PASS}}
            APPOPTIONS__REDIS_USERNAME= ${{secrets.REDIS_USERNAME}}

      - run: echo "${{ steps.deploy.outputs.url }}"